# Generated by Django 5.0.2 on 2024-03-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_job_m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_M',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('reader', 'Reader'), ('writter', 'Writter')], max_length=100),
        ),
    ]
