# Generated by Django 5.0.2 on 2024-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_describtion',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
