# Generated by Django 5.0.2 on 2024-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_blogmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/blog_pic'),
        ),
    ]
